# Generated by Django 5.1.8 on 2025-09-20 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='VerifiedBy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verification_image', models.ImageField(upload_to='media/verificationimage/')),
                ('surveyor_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_city', to='floodsApp.state')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tehsil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_tehsil', to='floodsApp.city')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer_image', models.ImageField(upload_to='media/farmerimage/')),
                ('farmerName', models.CharField(max_length=100)),
                ('fatherName', models.CharField(max_length=100)),
                ('mobileNumber', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('houseStatus', models.CharField(max_length=100)),
                ('totalLandOwned', models.CharField(max_length=100)),
                ('landAffected', models.CharField(max_length=100)),
                ('cropsPlanted', models.CharField(max_length=100)),
                ('cropsLost', models.CharField(max_length=100)),
                ('estimatedCropLoss', models.CharField(max_length=100)),
                ('tractorLeveling', models.CharField(max_length=100)),
                ('manureFertilizer', models.CharField(max_length=100)),
                ('seedsRequired', models.CharField(max_length=100)),
                ('fertilizersPesticides', models.CharField(max_length=100)),
                ('laborRequirement', models.CharField(max_length=100)),
                ('irrigationRepair', models.CharField(max_length=100)),
                ('livestockDamage', models.CharField(max_length=100)),
                ('householdNeeds', models.CharField(max_length=100)),
                ('housingRepair', models.CharField(max_length=100)),
                ('otherSupport', models.CharField(max_length=100)),
                ('additionalNotes', models.TextField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('vefified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verified_by', to='floodsApp.verifiedby')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=100)),
                ('pin_code', models.CharField(max_length=100)),
                ('tehsil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tehsil_village', to='floodsApp.tehsil')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TempPersonDataForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('temp_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_person_data_form', to='floodsApp.form')),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_person_village', to='floodsApp.village')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersonData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_data_form', to='floodsApp.form')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='person', to=settings.AUTH_USER_MODEL)),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_village', to='floodsApp.village')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
