# Generated by Django 5.1.8 on 2025-09-20 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('floodsApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Form',
            new_name='FarmerForm',
        ),
    ]
