# Generated by Django 5.1.8 on 2025-09-21 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floodsApp', '0002_rename_form_farmerform'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='persondata',
            options={'verbose_name_plural': 'Person Data'},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'verbose_name_plural': 'States'},
        ),
        migrations.AlterModelOptions(
            name='tehsil',
            options={'verbose_name_plural': 'Tehsils'},
        ),
        migrations.AlterModelOptions(
            name='temppersondataform',
            options={'verbose_name_plural': 'Temporary Person Data Forms'},
        ),
        migrations.AlterModelOptions(
            name='village',
            options={'verbose_name_plural': 'Villages'},
        ),
        migrations.AddField(
            model_name='city',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='persondata',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tehsil',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='temppersondataform',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='verifiedby',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='verifiedby',
            name='surveyor_mobile',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='village',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='farmerform',
            name='additionalNotes',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='farmerform',
            name='email',
            field=models.EmailField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='farmerform',
            name='fertilizersPesticides',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='farmerform',
            name='householdNeeds',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='farmerform',
            name='housingRepair',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='farmerform',
            name='irrigationRepair',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='farmerform',
            name='laborRequirement',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='farmerform',
            name='livestockDamage',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='farmerform',
            name='manureFertilizer',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='farmerform',
            name='otherSupport',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='farmerform',
            name='seedsRequired',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='farmerform',
            name='tractorLeveling',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(default='Punjab', max_length=50),
        ),
    ]
