# Generated by Django 5.1.8 on 2025-09-22 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floodsApp', '0003_alter_city_options_alter_persondata_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='persondata',
            name='temp_person_data_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_person', to='floodsApp.temppersondataform'),
        ),
    ]
