# Generated by Django 5.1.8 on 2025-09-22 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floodsApp', '0004_persondata_temp_person_data_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='persondata',
            name='is_single_user',
            field=models.BooleanField(default=False),
        ),
    ]
