# Generated by Django 5.1.8 on 2025-09-22 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('floodsApp', '0005_persondata_is_single_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmerform',
            old_name='vefified_by',
            new_name='verified_by',
        ),
    ]
