# Generated by Django 5.1.8 on 2025-09-24 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floodsApp', '0006_rename_vefified_by_farmerform_verified_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffectedVillageMapData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popup', models.CharField(max_length=100)),
                ('center', models.CharField(max_length=100)),
                ('zoom', models.CharField(default='14', max_length=100)),
                ('marker', models.CharField(max_length=100)),
                ('radius', models.CharField(default='600', max_length=100)),
                ('severity', models.CharField(max_length=100)),
                ('population', models.CharField(max_length=100)),
                ('village', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affected_villages_map', to='floodsApp.village')),
            ],
        ),
    ]
