# Generated by Django 5.1.8 on 2025-09-24 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floodsApp', '0007_affectedvillagemapdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affectedvillagemapdata',
            name='village',
        ),
        migrations.AddField(
            model_name='affectedvillagemapdata',
            name='pin_code',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='affectedvillagemapdata',
            name='center',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='affectedvillagemapdata',
            name='marker',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='affectedvillagemapdata',
            name='popup',
            field=models.CharField(help_text='village_display_name', max_length=100),
        ),
    ]
