# Generated by Django 5.1.8 on 2025-10-01 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floodsApp', '0008_remove_affectedvillagemapdata_village_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerform',
            name='farmer_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/farmerimage/'),
        ),
        migrations.AlterField(
            model_name='verifiedby',
            name='verification_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/verificationimage/'),
        ),
    ]
