# Generated by Django 5.1.8 on 2025-10-01 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floodsApp', '0009_alter_farmerform_farmer_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerform',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='village',
            name='latitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='village',
            name='longitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
