# Generated by Django 5.1.8 on 2025-10-05 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floodsApp', '0010_alter_farmerform_email_alter_village_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerform',
            name='amount_needed',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='farmerform',
            name='amount_received',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
