# Generated by Django 5.1.8 on 2025-10-16 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floodsApp', '0011_farmerform_amount_needed_farmerform_amount_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='affectedvillagemapdata',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='village_affected_data', to='floodsApp.village'),
        ),
        migrations.AlterField(
            model_name='farmerform',
            name='cropsLost',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='farmerform',
            name='cropsPlanted',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='farmerform',
            name='estimatedCropLoss',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='farmerform',
            name='farmerName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='farmerform',
            name='fatherName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='farmerform',
            name='houseStatus',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='farmerform',
            name='landAffected',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='farmerform',
            name='mobileNumber',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='farmerform',
            name='totalLandOwned',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='village',
            name='pin_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
