# Generated by Django 5.1.8 on 2025-12-02 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floodsApp', '0012_affectedvillagemapdata_village_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerform',
            name='additionalNotes',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='farmerform',
            name='fertilizersPesticides',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='farmerform',
            name='householdNeeds',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='farmerform',
            name='housingRepair',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='farmerform',
            name='irrigationRepair',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='farmerform',
            name='laborRequirement',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='farmerform',
            name='livestockDamage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='farmerform',
            name='manureFertilizer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='farmerform',
            name='otherSupport',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='farmerform',
            name='seedsRequired',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='farmerform',
            name='tractorLeveling',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
