"""
Django settings for floodsRelief project.

Generated by 'django-admin startproject' using Django 5.1.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from datetime import timedelta

from pathlib import Path


from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-+vh446ilmzs5jby@f1j$kbok08*w#300rw&vs=l2eooyq==n^^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    "srv1120260.hstgr.cloud",
    "openstreetmap.org",
    "www.openstreetmap.org",
    "nominatim.openstreetmap.org",
    "www.nominatim.openstreetmap.org",
    "72.61.171.121",
    "metabolicresetwithbob.com",
    "www.metabolicresetwithbob.com",
    "floodrelief.merapind.org",
    "www.floodrelief.merapind.org",
    "bobchris.jotinformatics.in",
    "www.bobchris.jotinformatics.in",
    "www.floodrelief.merapind.cloud",
    "floodrelief.merapind.cloud",

]




CORS_ALLOWED_ORIGINS = ["http://localhost:5173",
                        "https://openstreetmap.org",
                        "https://www.openstreetmap.org",
                        "https://nominatim.openstreetmap.org",
                        "http://72.61.171.121",
                        "https://metabolicresetwithbob.com",
                        "https://floodrelief.merapind.org",
                        "https://www.floodrelief.merapind.org",
                        "http://bobchris.jotinformatics.in",
                        "https://floodrelief.merapind.cloud",
                    ]

# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:5173",
#     "https://linkedinscrapper-f8ak.onrender.com",
#       "http://127.0.0.1:8000",
#       "http://31.97.233.53"
# ]


CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_ALL_ORIGINS = True 

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'accounts',
    'floodsApp',
    'adminDashboard',
    'dataAddition',
    'backendApp',
    'doctorApp',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'floodsRelief.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'dist')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    # 'DEFAULT_PERMISSION_CLASSES': [
    #     'rest_framework.permissions.IsAuthenticated',
    # ],
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
}


WSGI_APPLICATION = 'floodsRelief.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db_villages_data.sqlite3',
    }
}

AUTH_USER_MODEL='accounts.User'


AUTHENTICATION_BACKENDS = [
    'backendApp.api.auth_backend.EmailOrPhoneBackend',
    'django.contrib.auth.backends.ModelBackend',
]
# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/



STATIC_URL = 'static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_DIRS=[
    os.path.join(BASE_DIR,'dist'),
    os.path.join(BASE_DIR,'dist/.vite'),
    os.path.join(BASE_DIR,'dist/assets'),
    os.path.join(BASE_DIR,'dist/logo'),
    os.path.join(BASE_DIR,'dist/favicon'),
    os.path.join(BASE_DIR,'dist/fonts'),
]


CSRF_TRUSTED_ORIGINS = [
    "https://openstreetmap.org",
    "https://www.openstreetmap.org",
    "https://nominatim.openstreetmap.org",
    "http://72.61.171.121",
    "https://metabolicresetwithbob.com",
    "https://floodrelief.merapind.org",
    "http://localhost:5173",
    "http://bobchris.jotinformatics.in",
    "https://floodrelief.merapind.cloud",
    
]




import mimetypes

mimetypes.add_type("application/javascript", ".js", True)

mimetypes.add_type("text/css", ".css", True)



# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'




# Email Configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # Example for Gmail
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
ADMIN_EMAIL = os.getenv('ADMIN_EMAIL')

print("EMAIL_HOST_USER",EMAIL_HOST_USER)


RAZORPAY_KEY_ID = os.getenv("RAZORPAY_KEY_ID")
RAZORPAY_KEY_SECRET = os.getenv("RAZORPAY_KEY_SECRET")