# Generated by Django 5.1.8 on 2026-01-04 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorApp', '0003_product_productimage_feesmodel_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='product/pdf/'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user_slot',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='doctorApp.userslot'),
        ),
        migrations.CreateModel(
            name='ProductBuyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField(blank=True, null=True)),
                ('is_sold', models.BooleanField(default=False)),
                ('payment_status', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctorApp.product')),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='product_history',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paymnet_product', to='doctorApp.productbuyhistory'),
        ),
    ]
